import cv2
image = cv2.imread('example.png')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow("Original", image)
kernelElipse = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(20,5))
kernelRect = cv2.getStructuringElement(cv2.MORPH_RECT,(20,5))
kernelCross = cv2.getStructuringElement(cv2.MORPH_CROSS,(20,5))
erodedElipse = cv2.erode(gray,kernelElipse)
dilagedElipse = cv2.dilate(erodedElipse,kernelElipse)
openingElipse = cv2.morphologyEx(dilagedElipse,cv2.MORPH_OPEN,kernelElipse)
closingElipse = cv2.morphologyEx(openingElipse,cv2.MORPH_CLOSE,kernelElipse)
gradientElipse = cv2.morphologyEx(closingElipse,cv2.MORPH_GRADIENT,kernelElipse)
cv2.imshow("Modify",gradientElipse)
cv2.waitKey(0)
erodedCross = cv2.erode(gray,kernelCross)
dilagedCross = cv2.dilate(erodedCross,kernelCross)
openingCross = cv2.morphologyEx(dilagedCross,cv2.MORPH_OPEN,kernelCross)
closingCross = cv2.morphologyEx(openingCross,cv2.MORPH_CLOSE,kernelCross)
gradientCross = cv2.morphologyEx(closingCross,cv2.MORPH_GRADIENT,kernelCross)
cv2.imshow("ModifyCross",gradientCross)
cv2.waitKey(0)
